spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quiz_ai_online?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: quiz_ai_online
    password: change_me
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 1
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

file:
  upload-path: /www/wwwroot/quizAiOnline/uploads/

logging:
  level:
    com.quiz: info
    com.mybatisflex: warn
